const express = require('express')
const app = express()
const port = 3005
const bodyParser=require('body-parser')
const cors = require('cors')
const RouteA = require('./Route/app.route')
app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:false}))
app.use('/api',RouteA)
app.listen(port, () => console.log(`Example app listening on port ${port}!`))